### ISSUE TITLE
html_safe + interpolate (%) == boom

### ISSUE THREAD

**Issue by grosser** [svenfuchs/i18n#107]
``` Ruby
require 'i18n/core_ext/string/interpolate'
require 'active_support/core_ext/string/output_safety'
"%{a}" %{:a => 1} == '1' # fine
"%{a}".html_safe % {:a => 1} == '1' # BOOOM

NoMethodError: undefined method `to_sym' for nil:NilClass
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/i18n-0.6.0/lib/i18n/core_ext/string/interpolate.rb:92:in `%'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/activesupport-3.1.0/lib/active_support/core_ext/string/output_safety.rb:140:in `gsub'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/activesupport-3.1.0/lib/active_support/core_ext/string/output_safety.rb:140:in `gsub'
    from /usr/local/rvm/gems/ree-1.8.7-2011.03/gems/i18n-0.6.0/lib/i18n/core_ext/string/interpolate.rb:88:in `%'
    from (irb):4

```

**Comment by radar** [comment]
I can no longer reproduce this bug. I used the code from the OP.

```ruby
require 'i18n/core_ext/string/interpolate'
require 'active_support/core_ext/string/output_safety'
"%{a}" %{:a => 1} == '1' # fine
"%{a}".html_safe % {:a => 1} == '1' # No boom.
```

Closing this issue.
