### ISSUE TITLE
Key Value translation from redis problem with json

### ISSUE THREAD

**Issue by dukha** [svenfuchs/i18n#316]
ruby 2.1.3
rails 4.2.1
Trying to get translations out of redis via key_value.rb. I kept on getting JSON::ParserError: 795: unexpected token at json/common.rb 
def parse(source, opts = {})
    Parser.new(source, opts).parse
end
The only thing I have been able to do to work around this is to modify I18n::Backend::KeyValue
as  
```ruby
def lookup(locale, key, scope = [], options = {})
    key   = normalize_flat_keys(locale, key, scope, options[:separator])
    value = @store["#{locale}.#{key}"]
    value = ActiveSupport::JSON.decode(value) if value
    value.is_a?(Hash) ? value.deep_symbolize_keys : value
 end
```
by adding json stuff to keep decode happy
```ruby
def lookup(locale, key, scope = [], options = {})
     key   = normalize_flat_keys(locale, key, scope, options[:separator])
     value = @store["#{locale}.#{key}"]
     value = ActiveSupport::JSON.decode("[\"" + value + "\"]")[0] if value
     value.is_a?(Hash) ? value.deep_symbolize_keys : value
 end
```
Is this a bug or could there be a problem somewhere else?

**Comment by radar** [comment]
@dukha could you please provide steps to reproduce this issue?

**Comment by yamashita-mg** [comment]
ruby 2.3.0
rails 5.0.0.1
redis-server 3.2.5

same to me...
when I tried to receive word which published through redis-cli in rails project of actioncable.

**Comment by absessive** [comment]
Just had this happen to me as well
redis-server 3.0.5
ruby 2.2.2
rails 5.0.0.1

My initializer looks like this.

    $redis = Redis::Namespace.new("my_app", redis: Redis.new)
    I18n.backend = I18n::Backend::Chain.new(I18n::Backend::KeyValue.new($redis), I18n.backend)

In Rails Console added a key

    > $redis.set("en.hello", "Hello in English")

On reloading the console

   > I18n.t("hello")

results in
```
JSON::ParserError: 795: unexpected token at 'Hello in English'
	from /Users/absessive/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/json/common.rb:155:in `parse'
	from /Users/absessive/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/json/common.rb:155:in `parse'
	from /Users/absessive/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0.1/lib/active_support/json/decoding.rb:21:in `decode'
	from /Users/absessive/.rvm/gems/ruby-2.2.2/gems/i18n-0.7.0/lib/i18n/backend/key_value.rb:92:in `lookup'
	from /Users/absessive/.rvm/gems/ruby-2.2.2/gems/i18n-0.7.0/lib/i18n/backend/base.rb:26:in `translate'
	from /Users/absessive/.rvm/gems/ruby-2.2.2/gems/i18n-0.7.0/lib/i18n/backend/chain.rb:46:in `block (2 levels) in translate'
	from /Users/absessive/.rvm/gems/ruby-2.2.2/gems/i18n-0.7.0/lib/i18n/backend/chain.rb:44:in `catch'
	from /Users/absessive/.rvm/gems/ruby-2.2.2/gems/i18n-0.7.0/lib/i18n/backend/chain.rb:44:in `block in translate'
	from /Users/absessive/.rvm/gems/ruby-2.2.2/gems/i18n-0.7.0/lib/i18n/backend/chain.rb:43:in `each'
	from /Users/absessive/.rvm/gems/ruby-2.2.2/gems/i18n-0.7.0/lib/i18n/backend/chain.rb:43:in `translate'
	from /Users/absessive/.rvm/gems/ruby-2.2.2/gems/i18n-0.7.0/lib/i18n.rb:158:in `block in translate'
	from /Users/absessive/.rvm/gems/ruby-2.2.2/gems/i18n-0.7.0/lib/i18n.rb:154:in `catch'
	from /Users/absessive/.rvm/gems/ruby-2.2.2/gems/i18n-0.7.0/lib/i18n.rb:154:in `translate'
	from (irb):27
	from /Users/absessive/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/commands/console.rb:65:in `start'
	from /Users/absessive/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/absessive/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/absessive/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/absessive/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:9:in `require'
```

**Comment by stereobooster** [comment]
because you need JSON encode values before you store them in Redis

```
$redis.set("en.hello", ActiveSupport::JSON.encode("Hello in English"))
```
