### ISSUE TITLE
Tests failing on ruby 2.2

### ISSUE THREAD

**Issue by Bartuz** [svenfuchs/i18n#324]
```
 ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
```

runing with: `bundle exec rake test`

```
not testing with Cache enabled because active_support can not be found
Skipping cache tests using ActiveSupport
Run options: --seed 23734

# Running:

........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................E......E........................................................................................................................................................................................................................................................................................................................

Finished in 0.385754s, 2799.7117 runs/s, 3971.4429 assertions/s.

  1) Error:
I18nAllFeaturesApiTest#test_lookup:_it_returns_a_native_false:
RuntimeError: can't modify frozen FalseClass
    /Users/filip/dev/ah/lib/i18n/backend/metadata.rb:24:in `translation_metadata'
    /Users/filip/dev/ah/lib/i18n/backend/metadata.rb:47:in `interpolate'
    /Users/filip/dev/ah/lib/i18n/backend/base.rb:41:in `translate'
    /Users/filip/dev/ah/lib/i18n/backend/metadata.rb:43:in `block in translate'
    /Users/filip/dev/ah/lib/i18n/backend/metadata.rb:58:in `with_metadata'
    /Users/filip/dev/ah/lib/i18n/backend/metadata.rb:43:in `translate'
    /Users/filip/dev/ah/lib/i18n/backend/cache.rb:66:in `translate'
    /Users/filip/dev/ah/lib/i18n/backend/fallbacks.rb:45:in `block (2 levels) in translate'
    /Users/filip/dev/ah/lib/i18n/backend/fallbacks.rb:44:in `catch'
    /Users/filip/dev/ah/lib/i18n/backend/fallbacks.rb:44:in `block in translate'
    /Users/filip/dev/ah/lib/i18n/backend/fallbacks.rb:42:in `each'
    /Users/filip/dev/ah/lib/i18n/backend/fallbacks.rb:42:in `translate'
    /Users/filip/dev/ah/lib/i18n/backend/chain.rb:46:in `block (2 levels) in translate'
    /Users/filip/dev/ah/lib/i18n/backend/chain.rb:44:in `catch'
    /Users/filip/dev/ah/lib/i18n/backend/chain.rb:44:in `block in translate'
    /Users/filip/dev/ah/lib/i18n/backend/chain.rb:43:in `each'
    /Users/filip/dev/ah/lib/i18n/backend/chain.rb:43:in `translate'
    /Users/filip/dev/ah/lib/i18n.rb:158:in `block in translate'
    /Users/filip/dev/ah/lib/i18n.rb:154:in `catch'
    /Users/filip/dev/ah/lib/i18n.rb:154:in `translate'
    /Users/filip/dev/ah/lib/i18n/tests/lookup.rb:29:in `block in <module:Lookup>'


  2) Error:
I18nAllFeaturesApiTest#test_lookup:_it_returns_a_native_true:
RuntimeError: can't modify frozen TrueClass
    /Users/filip/dev/ah/lib/i18n/backend/metadata.rb:24:in `translation_metadata'
    /Users/filip/dev/ah/lib/i18n/backend/metadata.rb:47:in `interpolate'
    /Users/filip/dev/ah/lib/i18n/backend/base.rb:41:in `translate'
    /Users/filip/dev/ah/lib/i18n/backend/metadata.rb:43:in `block in translate'
    /Users/filip/dev/ah/lib/i18n/backend/metadata.rb:58:in `with_metadata'
    /Users/filip/dev/ah/lib/i18n/backend/metadata.rb:43:in `translate'
    /Users/filip/dev/ah/lib/i18n/backend/cache.rb:66:in `translate'
    /Users/filip/dev/ah/lib/i18n/backend/fallbacks.rb:45:in `block (2 levels) in translate'
    /Users/filip/dev/ah/lib/i18n/backend/fallbacks.rb:44:in `catch'
    /Users/filip/dev/ah/lib/i18n/backend/fallbacks.rb:44:in `block in translate'
    /Users/filip/dev/ah/lib/i18n/backend/fallbacks.rb:42:in `each'
    /Users/filip/dev/ah/lib/i18n/backend/fallbacks.rb:42:in `translate'
    /Users/filip/dev/ah/lib/i18n/backend/chain.rb:46:in `block (2 levels) in translate'
    /Users/filip/dev/ah/lib/i18n/backend/chain.rb:44:in `catch'
    /Users/filip/dev/ah/lib/i18n/backend/chain.rb:44:in `block in translate'
    /Users/filip/dev/ah/lib/i18n/backend/chain.rb:43:in `each'
    /Users/filip/dev/ah/lib/i18n/backend/chain.rb:43:in `translate'
    /Users/filip/dev/ah/lib/i18n.rb:158:in `block in translate'
    /Users/filip/dev/ah/lib/i18n.rb:154:in `catch'
    /Users/filip/dev/ah/lib/i18n.rb:154:in `translate'
    /Users/filip/dev/ah/lib/i18n/tests/lookup.rb:25:in `block in <module:Lookup>'

1080 runs, 1532 assertions, 0 failures, 2 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -w -I"lib:lib:test" -I"/Users/filip/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0" "/Users/filip/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/**/*_test.rb" ]
/Users/filip/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/Users/filip/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by Bartuz** [comment]
It happens because these methods: https://github.com/svenfuchs/i18n/blob/master/lib/i18n/backend/metadata.rb#L22-L30 try to modify instance variable inside true/false class which are frozen  (https://bugs.ruby-lang.org/issues/8923)

These setters and getters are initialised called here: https://github.com/svenfuchs/i18n/blob/master/lib/i18n/backend/metadata.rb#L47

I'm just curious why it doesn't fail on other frozen classes like `Fixnum` or `Symbol`. #edit - Because this method is never called with symbol/fixnum class :)

For debugging purposes I prepended `binding.pry if entry == true || false` in https://github.com/svenfuchs/i18n/blob/master/lib/i18n/backend/metadata.rb#L47 . 

Maybe these true/false tests are useless? I'm not quite sure what functionality they really test. https://github.com/svenfuchs/i18n/commit/73dc34bb82e02429941f7dde6e70f7dfbab40751#diff-c97f106685f92dbd8a677b3e77b1b1b4R25

**Comment by atzorvas** [comment]
is there any update on this one?

**Comment by Bartuz** [comment]
Haven't touched this since last post

**Comment by atzorvas** [comment]
#310 is relevant
#305 solve this, but it's not merged yet.

**Comment by radar** [comment]
#305 has been merged into master, and it solves this issue. Thanks everyone for reporting it!
