### ISSUE TITLE
Unfriendly error message when parsing YAML

### ISSUE THREAD

**Issue by qoobaa** [svenfuchs/i18n#88]
There's no way to find the broken file... Maybe we can display something more developer friendly here? :-)

```
I18n.backend.send(:init_translations)
Psych::SyntaxError: couldn't parse YAML at line 16 column 14
    from /web/tt/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/psych.rb:148:in `parse'
from /web/tt/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/psych.rb:148:in `parse_stream'
from /web/tt/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/psych.rb:119:in `parse'
from /web/tt/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/psych.rb:106:in `load'
from /web/tt/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/psych.rb:205:in `load_file'
from /web/tt/production/shared/bundle/ruby/1.9.1/gems/i18n-0.5.0/lib/i18n/backend/base.rb:170:in `load_yml'
from /web/tt/production/shared/bundle/ruby/1.9.1/gems/i18n-0.5.0/lib/i18n/backend/base.rb:156:in `load_file'
from /web/tt/production/shared/bundle/ruby/1.9.1/gems/i18n-0.5.0/lib/i18n/backend/base.rb:15:in `block in load_translations'
from /web/tt/production/shared/bundle/ruby/1.9.1/gems/i18n-0.5.0/lib/i18n/backend/base.rb:15:in `each'
from /web/tt/production/shared/bundle/ruby/1.9.1/gems/i18n-0.5.0/lib/i18n/backend/base.rb:15:in `load_translations'
from /web/tt/production/shared/bundle/ruby/1.9.1/gems/i18n-0.5.0/lib/i18n/backend/simple.rb:55:in `init_translations'
from (irb):1
from /web/tt/production/shared/bundle/ruby/1.9.1/gems/railties-3.0.7/lib/rails/commands/console.rb:44:in `start'
from /web/tt/production/shared/bundle/ruby/1.9.1/gems/railties-3.0.7/lib/rails/commands/console.rb:8:in `start'
from /web/tt/production/shared/bundle/ruby/1.9.1/gems/railties-3.0.7/lib/rails/commands.rb:23:in `<top (required)>'
from ./script/rails:6:in `require'
from ./script/rails:6:in `<main>'
```

**Comment by radar** [comment]
`YAML.load_file` in recent Ruby versions shows an error with the filename:

```
Psych::SyntaxError: (config/locales/pl.yml): mapping values are not allowed in this context at line 9 column 9
```
